### ISSUE TITLE
OSError: SimianLuo/LCM_Dreamshaper_v7 does not appear to have a file named scheduler_config.json

### ISSUE THREAD

**Issue by jasoncow007** [0xbitches/sd-webui-lcm#28]
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\diffusers\configuration_utils.py", line 370, in load_config
    config_file = hf_hub_download(
  File "<enhanced_experience patches.hfmirror.huggingface_hub>", line 62, in hf_hub_download_wrapper_inner
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-lcm\scripts\main.py", line 97, in generate
    scheduler = LCMScheduler.from_pretrained(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 140, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\diffusers\configuration_utils.py", line 397, in load_config
    raise EnvironmentError(
OSError: SimianLuo/LCM_Dreamshaper_v7 does not appear to have a file named scheduler_config.json.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by jasoncow007** [comment]
cannot download dreamshaper automaticly, where to download and put manually
