### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by noorhamadani** [0xbitches/sd-webui-lcm#3]
I am getting following Error:

Loading pipeline components...:  83%|███████████████████████████████████████████▎        | 5/6 [00:00<00:00,  5.68it/s]
*** Error loading script: main.py
    Traceback (most recent call last):
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\extensions\sd-webui-lcm\scripts\main.py", line 72, in <module>
        pipe = LatentConsistencyModelPipeline.from_pretrained(
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in from_pretrained
        loaded_sub_model = load_sub_model(
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 472, in load_sub_model
        loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
        return cls._from_pretrained(
      File "C:\Users\agide\Stable Diffusion\Automatic1111\sd.webui\webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2044, in _from_pretrained
        raise ValueError(
    ValueError: Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.

**Comment by 0xbitches** [comment]
This is covered in the README: https://github.com/0xbitches/sd-webui-lcm#known-issues.
