### ISSUE TITLE
[bug] when using --no-gradio-queue, report "ValueError: Progress tracking requires queuing to be enabled"

### ISSUE THREAD

**Issue by ParticleDog** [0xbitches/sd-webui-lcm#43]
Traceback (most recent call last):
  File "D:\Projects\stable-diffusion\execution\original\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\Projects\stable-diffusion\execution\original\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "D:\Projects\stable-diffusion\execution\original\stable-diffusion-webui\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\Projects\stable-diffusion\execution\original\stable-diffusion-webui\webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "C:\Users\gdfs_\.conda\envs\stable_diffusion\lib\site-packages\gradio\blocks.py", line 1858, in launch
    self.validate_queue_settings()
  File "C:\Users\gdfs_\.conda\envs\stable_diffusion\lib\site-packages\gradio\blocks.py", line 1690, in validate_queue_settings
    raise ValueError("Progress tracking requires queuing to be enabled.")
ValueError: Progress tracking requires queuing to be enabled.

reference: https://github.com/v8hid/infinite-zoom-automatic1111-webui/issues/32
FYI

**Comment by DangerCow** [comment]
--no-gradio-queue with this extension seems to completely crash a1111 without any error or warning when loading a model
