### ISSUE TITLE
SD WebUI  v1.6.0 不能用你这个 sd-webui-lcm？

### ISSUE THREAD

**Issue by pendave** [0xbitches/sd-webui-lcm#44]
*** Error loading script: main.py
    Traceback (most recent call last):
      File "G:\SD\01-01HH\novelai-webui-aki-v3A\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\SD\01-01HH\novelai-webui-aki-v3A\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\SD\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-lcm\scripts\main.py", line 7, in <module>
        from lcm.lcm_i2i_pipeline import LatentConsistencyModelImg2ImgPipeline
      File "G:\SD\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-lcm\lcm\lcm_i2i_pipeline.py", line 28, in <module>
        from diffusers.image_processor import VaeImageProcessor, PipelineImageInput
    ImportError: cannot import name 'PipelineImageInput' from 'diffusers.image_processor' (G:\SD\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\diffusers\image_processor.py)

我的 SD WebUI 版本是 ：
version: [v1.6.0-2-g4afaaf8a]•  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.21  •  gradio: 3.41.2

diffusers 也是最新版本

**Comment by zq52121** [comment]
我的也出现这种情况，不显示lcm选项卡

**Comment by axhello** [comment]
pip install --upgrade diffusers  # make sure to use at least diffusers >= 0.22

**Comment by onijack888** [comment]
python -m pip install --upgrade pip，升级到0.23，问题依然存在

**Comment by Hansimov** [comment]
You should go to the venv path of sd-webui, and use the python executable there to upgrade the `diffusers`,
instead of using the `python` command recoginized in your system env path.

See the link below for more details:
* https://github.com/0xbitches/sd-webui-lcm#1-cant-find-lcm-tab-or-importerror-cannot-import-name-xxx-from-diffusersxxx

**Comment by yangxin114** [comment]
in  {sd-webui-root}/moudles/launch_utils.py ,in method prepare_environment,   add  script: 
run_pip("install --upgrade diffusers", "diffusers")
