### ISSUE TITLE
Starting CPU only tryies to use CUDA which results in error

### ISSUE THREAD

**Issue by DevilaN** [0xbitches/sd-webui-lcm#5]
Loading pipeline components...:   0% 0/6 [00:00<?, ?it/s]
Loading pipeline components...:  17% 1/6 [00:00<00:00,  5.49it/s]
Loading pipeline components...:  67% 4/6 [00:00<00:00,  8.86it/s]
Loading pipeline components...:  83% 5/6 [00:00<00:00,  6.52it/s]
Loading pipeline components...: 100% 6/6 [00:00<00:00,  7.42it/s]
webui-docker-auto-cpu-1  | *** Error loading script: main.py
webui-docker-auto-cpu-1  |     Traceback (most recent call last):
webui-docker-auto-cpu-1  |       File "/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
webui-docker-auto-cpu-1  |         script_module = script_loading.load_module(scriptfile.path)
webui-docker-auto-cpu-1  |       File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
webui-docker-auto-cpu-1  |         module_spec.loader.exec_module(module)
webui-docker-auto-cpu-1  |       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-cpu-1  |       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-cpu-1  |       File "/stable-diffusion-webui/extensions/sd-webui-lcm/scripts/main.py", line 75, in <module>
webui-docker-auto-cpu-1  |         pipe.to("cuda")
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 733, in to
webui-docker-auto-cpu-1  |         module.to(torch_device, torch_dtype)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1902, in to
webui-docker-auto-cpu-1  |         return super().to(*args, **kwargs)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
webui-docker-auto-cpu-1  |         return self._apply(convert)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
webui-docker-auto-cpu-1  |         module._apply(fn)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
webui-docker-auto-cpu-1  |         module._apply(fn)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
webui-docker-auto-cpu-1  |         module._apply(fn)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
webui-docker-auto-cpu-1  |         param_applied = fn(param)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
webui-docker-auto-cpu-1  |         return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
webui-docker-auto-cpu-1  |       File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
webui-docker-auto-cpu-1  |         torch._C._cuda_init()
webui-docker-auto-cpu-1  |     RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by 0xbitches** [comment]
Adding fastsd cpu integration to my todo list...

**Comment by 0xbitches** [comment]
Completed in https://github.com/0xbitches/sd-webui-lcm/commit/bddc54285be81b0c45320d6ba9edc8d93fe39806
