### ISSUE TITLE
unable to install LCM

### ISSUE THREAD

**Issue by boomboom77365** [0xbitches/sd-webui-lcm#6]
The config attributes {'force_upcast': True} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
*** Error loading script: main.py
    Traceback (most recent call last):
      File "E:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-lcm\scripts\main.py", line 71, in <module>
        pipe = LatentConsistencyModelPipeline.from_pretrained(
      File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1039, in from_pretrained
        loaded_sub_model = load_sub_model(
      File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
        loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
      File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 583, in from_pretrained
        raise ValueError(
    ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from C:\Users\Tr0uble\.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\snapshots\c7f9b672c65a664af57d1de926819fd79cb26eb8\vae because the following keys are missing:
     decoder.mid_block.attentions.0.value.weight, decoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.value.bias, decoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.query.bias, encoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.value.bias, decoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.key.weight, encoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.proj_attn.weight, decoder.mid_block.attentions.0.key.weight.
     Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

**Comment by 0xbitches** [comment]
Looks like the model download failed. Can you try deleting the huggingface model cache folder`C:\Users\Tr0uble.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\`, then restart the UI?

**Comment by boomboom77365** [comment]
> Looks like the model download failed. Can you try deleting the huggingface model cache folder`C:\Users\Tr0uble.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\`, then restart the UI?

I've deleted the Dreamshaper  v7 model and let it download again.

The config attributes {'force_upcast': True} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
*** Error loading script: main.py
    Traceback (most recent call last):
      File "E:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-lcm\scripts\main.py", line 71, in <module>
        pipe = LatentConsistencyModelPipeline.from_pretrained(
      File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1039, in from_pretrained
        loaded_sub_model = load_sub_model(
      File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
        loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
      File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 583, in from_pretrained
        raise ValueError(
    ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from C:\Users\Tr0uble\.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\snapshots\c7f9b672c65a664af57d1de926819fd79cb26eb8\vae because the following keys are missing:
     encoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.query.weight, encoder.mid_block.attentions.0.proj_attn.bias, decoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.query.bias, encoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.key.weight, encoder.mid_block.attentions.0.value.weight, decoder.mid_block.attentions.0.value.weight, decoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.value.bias.
     Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

Still got hit by this. Is there anything else I can try?

**Comment by 0xbitches** [comment]
Can you check the version of `diffusers` you have in `E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\`? There is a chance it is outdated.

**Comment by Talae06** [comment]
@boomboom77365 @0xbitches Had the same problem, diffusers version was 0.16.1, upgrading it to latest 0.21.4 did the trick indeed. Thanks :)

**Comment by 2blackbar** [comment]
let us download model on our own just update docs where to keep it, autodownloading from hface is crap

**Comment by miwgel** [comment]
On comfyui I had to run this from the same virtual environment in a new .py file:
```python
from diffusers import StableDiffusionPipeline

repo_id = "SimianLuo/LCM_Dreamshaper_v7"
pipe = StableDiffusionPipeline.from_pretrained(repo_id, use_safetensors=True)
```

That downloads the model to the folder the comfyui node expects. Try it in Auto1111

**Comment by jFkd1** [comment]
@2blackbar diffusers has a pretty good doc already.
https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/overview#diffusers.DiffusionPipeline.from_pretrained

**Comment by 0xbitches** [comment]
@2blackbar As @jFkd1 said, the `diffusers` library already supports loading models locally. To do that, simple replace the repo id (`"SimianLuo/LCM_Dreamshaper_v7"`) in line 69 - 72 of `scripts/main.py` with the path to your local model directory.

**Comment by boomboom77365** [comment]
> @2blackbar As @jFkd1 said, the `diffusers` library already supports loading models locally. To do that, simple replace the repo id (`"SimianLuo/LCM_Dreamshaper_v7"`) in line 69 - 72 of `scripts/main.py` with the path to your local model directory.

can I load any models or does it have to be dreamshaper v7?

**Comment by AugmentedRealityCat** [comment]
> can I load any models or does it have to be dreamshaper v7?

As of now it's the only model that works with it. @0xbitches is very clear about it in the readme:

> Note that LCMs are a completely different class of models than Stable Diffusion, and the only available checkpoint currently is [LCM_Dreamshaper_v7](https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7).

taken from: https://github.com/0xbitches/sd-webui-lcm#latent-consistency-model-for-stable-diffusion-webui

**Comment by boomboom77365** [comment]
> > can I load any models or does it have to be dreamshaper v7?
> 
> As of now it's the only model that works with it. @0xbitches is very clear about it in the readme:
> 
> > Note that LCMs are a completely different class of models than Stable Diffusion, and the only available checkpoint currently is [LCM_Dreamshaper_v7](https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7).
> 
> taken from: https://github.com/0xbitches/sd-webui-lcm#latent-consistency-model-for-stable-diffusion-webui

Understood. Is there a way that I can get it working? Tried all the recommendations.

**Comment by navalguijo** [comment]
I get the same Error, already tried solutions suggested here and no luck. Still don't get LCM tab. Any other ideas?

I get this in the startup:

The config attributes {'addition_time_embed_dim': None, 'attention_type': 'default', 'dropout': 0.0, 'encoder_hid_dim_type': None, 'num_attention_heads': None, 'transformer_layers_per_block': 1} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.3.44G/3.44G [01:11<00:00, 80.9MB/s]
The config attributes {'force_upcast': True} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
*** Error loading script: main.py
    Traceback (most recent call last):
      File "Y:\Automatic1111_130\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "Y:\Automatic1111_130\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Y:\Automatic1111_130\stable-diffusion-webui\extensions\sd-webui-lcm\scripts\main.py", line 71, in <module>
        pipe = LatentConsistencyModelPipeline.from_pretrained(
      File "Y:\Automatic1111_130\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1039, in from_pretrained
        loaded_sub_model = load_sub_model(
      File "Y:\Automatic1111_130\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
        loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
      File "Y:\Automatic1111_130\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 583, in from_pretrained
        raise ValueError(
    ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from C:\Users\navalNew03\.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\snapshots\fb9c5d167af11fd84454ae6493878b10bb63b067\vae because the following keys are missing:
     decoder.mid_block.attentions.0.query.weight, encoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.proj_attn.weight, decoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.key.weight, encoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.value.bias.
     Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

**Comment by Matti-Koopa** [comment]
So did anyone find a solution that works on a clean install? Need this for a docker environment.

**Comment by BryceBarbara** [comment]
@navalguijo Make sure you install the updated diffusers version in the venv and not globally. I made that mistake initially and got the same result.

**Comment by boomboom77365** [comment]
> @navalguijo Make sure you install the updated diffusers version in the venv and not globally. I made that mistake initially and got the same result.

so cmd in the venv of stable diffusion and pip install --upgrade diffusers[torch]?
